name: clean_architecture_flutter
description: "Clean architecture flutter with SqfLite, RiverPod, GetIt and HTTP"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  path: ^1.9.0
  sqflite: ^2.3.3
  get_it: ^7.7.0
  flutter_riverpod: ^2.5.1
  
  # default dependecy
  cupertino_icons: ^1.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli.ttf